apiVersion: v2
name: dbt-on-k8s
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: airflow
    version: "1.4.0"
    repository: "https://airflow.apache.org"
    condition: "airflow.enabled"
  - name: postgres-operator
    version: "1.7.1"
    repository: "https://ckotzbauer.github.io/helm-charts"
    condition: "postgres_operator.enabled"