# Override the default values.yaml
# Airflow executor
# Options: LocalExecutor, CeleryExecutor, KubernetesExecutor, CeleryKubernetesExecutor
executor: "KubernetesExecutor"
# Ingress configuration
ingress:
  # Enable ingress resource
  enabled: true
  # Configs for the Ingress of the web Service
  web:
    # The hostnames or hosts configuration for the web Ingress
    hosts:
      - name: "airflow-192.168.64.2.nip.io"
        # configs for web Ingress TLS
        tls:
          # Enable TLS termination for the web Ingress
          enabled: false
          # the name of a pre-created Secret containing a TLS private key and certificate
          secretName: ""