{{- if .Values.postgres_dwh.enabled -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  databases: {}
  preparedDatabases:
    dwh:
      defaultUsers: true
      schemas:
        demo:
          # Disable the schema specific roles as we only use one schema. This
          # will allow the database users to control the schema.
          defaultRoles: false
  postgresql:
    version: "14"
{{- end -}}
