{{- if .Values.postgres_dwh.enabled -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  databases: {}
  preparedDatabases:
    dwh:
      # defaultUsers: true
      schemas:
        dev:
          defaultUsers: true
          defaultRoles: true
        prod:
          defaultUsers: true
          defaultRoles: true
  postgresql:
    version: "14"
{{- end -}}
